### ISSUE TITLE
Odczytywanie parametrów z pliku ( prezent dla Franca)

### ISSUE THREAD

**Issue by PiotrFoltyniewicz** [ddf172/Ecosystem-Simulation#23]
Zrobić jakąś klasę, która bierze plik json i odczytuje te parametry i zapisuje w klasie SimulationParameters czy coś takiego,
Potem te parametry będą użyte, żeby rozpocząć symulację.
Samą strukturę pliku json też możesz stworzyć

Są tutaj podzi

Potrzebne parametry: (jak ktoś coś uważa, że jeszcze dodatkowe lub jakieś niepotrzebne to niech komentuje)

Parametry ogólne:
- [x] mapWidth
- [x] mapHeight
- [x] randomGrassProbability -> (szansa na tile z trawą w przypadku generowania losowego)
- [x] maxTurnLimit
- [ ] energyLossMultiplier

Parametry jedzenia
- [x] maxGrassGrowth -> (wartość do jakiej ilości trawa może maksymalnie urosnąć)
- [x] grassRegrowAmount -> (o ile rośnie trawa za każdy regrow)
- [x] grassRegrowCooldown -> (ilość tur pomiędzy każdym regrow trawy)
- [ ] animalMeatDrop -> (ile zabite zwierzę zostawia mięsa)

Parametry herbivoreAnimal
- [x] startingHerbivoreAnimalCount
- [x] herbivoreAnimalSpeed
- [x] herbivoreAnimalMaxEnergy
- [x] herbivoreAnimalSightRange
- [x] herbivoreAnimalStrength

Parametry carnivoreAnimal
- [x] startingCarnivoreAnimalCount
- [x] carnivoreAnimalSpeed
- [x] carnivoreAnimalMaxEnergy
- [x] carnivoreAnimalSightRange
- [x] carnivoreAnimalStrength

**Comment by Petrerer** [comment]
Te dwie rzeczy co zostały jakoś inaczej już liczymy więc nie ma sensu żeby je zczytywać z pliku
