### ISSUE TITLE
Statystyki symulacji

### ISSUE THREAD

**Issue by PiotrFoltyniewicz** [ddf172/Ecosystem-Simulation#24]
Zrobić klasę, która w konstruktorze bierze wskaźniki do vector<Animal*> oraz Grid*  i na podstawie zawartych tam danych oblicza różne statystyki. Powinna mieć różne funkcje, które potem będą wywoływane co turę w SimulationManager. A następnie ogarnie się, żeby były wyświetlane na bieżąco obok mapy (ale to osobny issue).

Przykładowe statystyki:
- ilość zwierząt danego gatunku
- łączna wartość energii trawy na mapie
- łączna wartość energii mięsa na mapie

Szczerze idk XD chciałem jakieś fajne statystyki ale nie mam pomysłu. Ale na pewno się przydadzą.

**Comment by Petrerer** [comment]
Basic staty + wykres
