### ISSUE TITLE
SimulationManager implementacja

### ISSUE THREAD

**Issue by PiotrFoltyniewicz** [ddf172/Ecosystem-Simulation#7]
W środku powinny być 2 listy (może będzie użyty ten generyczny container). Jedna dla zwierząt, a druga dla trawy XD, żeby co turę aktualizować brakującą ilość tur do odrośnięcia. Jak ktoś ma pomysł na lepszą implementację to śmiało

**Comment by PiotrFoltyniewicz** [comment]
Na ten moment gotowe, czekamy na więcej implementacji action

**Comment by ddf172** [comment]
Więcej implementacji action dodane czekam na implementacje statystyk do managera
